//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorisation.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id_Client { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Id_Gender { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
    }
}
